### ISSUE TITLE
Revisit kotlin scripts and event handling

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#751]
Unfortunately kotlin scripts aren't supported very well by kotlin 2.0.0+ due to a multitude of errors with the k2 compiler and intellij support:

- Compiling scripts in source root isn't supported, can be enabled with -Xallow-any-scripts-in-source-roots and -Xuse-fir-lt=false flags
- -Xuse-fir-lt=false means value classes can't be used in certain cases: https://youtrack.jetbrains.com/issue/KT-54513/NoSuchMethodError-on-access-to-value-class-implementing-an-interface-from-another-module
- Sometimes compiling complex scripts gives: https://youtrack.jetbrains.com/issue/KT-59114/Backend-Internal-error-Exception-during-IR-lowering
- Using scripts across modules breaks references: https://youtrack.jetbrains.com/issue/KTIJ-32835/Broken-resolution-when-referencing-declaration-from-another-module-in-custom-script
- https://youtrack.jetbrains.com/issue/KTIJ-32839/Custom-scripts-always-resolve-into-class-files-even-when-sources-are-available
- Compile and reload no longer works for scripts https://youtrack.jetbrains.com/issue/KTIJ-33370/Debugger-Inaccessible-Compile-and-Reload-Modified-Files-button-for-Kotlin-scripts
- And intelli-sense generally just breaks.

The options are:
1. Keep scripting as is, and don't upgrade from 1.9.22 for the foreseeable future.
This means missing out on new features, and will become more problematic with library versions as I've already found trying to use ksp

2. Write a kotlin compiler or gradle script to compile separately
Unsure how feasible this is and while it would solve 2.0 support it doesn't help with the intelli-sense problems.

3. Switch to a different scripting language - LUA
Performance implications aren't known
It's a new language to learn
Will be unfamiliar to contributors too
Might not work well with coroutines async/language differences

4. Switch to using regular kotlin files

There's multiple ways of doing this.
RSMod switched to classes with a startup function

```kotlin
class LumbridgeScript : PluginScript() {
    override fun ScriptContext.startup() {
        // Call operations
    }
}
class CanoeScript {
    init {
        objectOperate("Chop-down", "canoe_station") {

        }
    }
}
```

This could be done a bit more stylistically:

```kotlin
class CanoeScript : TestScript({
    objectOperate("Chop-down", "canoe_station") {

    }
})

// This would pollute top level variables
val canoeScript: ObjectOption<Player>.() -> Unit = @Operate {

}
val canoeScript = Script {

}
```
but is still quite hacky trying to emulate the way scripting works, it is at least compatible with the existing calls and wouldn't require too much work to migrate.

The other way about going about it would be to annotate top-level functions in .kt classes, so rather than replace scripts, replace event subscribers with methods instead.

```kotlin
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.SOURCE)
annotation class ObjectOperate(
    val option: String,
    val objects: Array<String>,
    val npc: String = "*",
    val arrive: Boolean = true,
)

@ObjectOperate(option = "Chop-down", objs = ["canoe_station"])
suspend fun chopDownCanoe(player: Player, target: GameObject, def: ObjectDefinition, option: String) {

}

@Script(event = "player_operate_object", option = "Chop-down", ids = ["canoe_station"])
suspend fun ObjectOption<Player>.operateObjectCanoe() {

}

objectOperate("option", "objects", block = ObjectOption<Player>::operateObjectCanoe)


@Event(Type.ObjectOperate, option = "Chop-down", ids = ["canoe_station"])
suspend fun ObjectOption<Player>.operateObjectCanoe() {
}
```

Cons:
- Every method needs to be named uniquely
- Massive undertaking to rewrite
- ~~Can't use `inject()` in classes~~ (actually you can use if private it would seem)

Pros:
- More "standard" looking
- No future kts issues
- Annotations would allow ksp generation so essentially an almost-zero "script" loading time
- Would work with compile and reload
- Could do parameter dependency injection

**Comment by GregHib** [comment]
Done some exploring

[Annotation based ksp solution](https://github.com/GregHib/void/tree/921ef2f0b80ab4435c37e6f9ac34eb7d7d513ca8) works but needs improvement so calls are more direct and not in a tree in order to load faster. The syntax is questionable, it's nice having no indentation and everything top level, however it means having to name all methods uniquely and pollutes suggestions when using extensions. It would also be a lot of work to convert all scripts. 

Lambda class script won't work due to it being more akin to inside a method rather than a class, so lots of features like nested class and method ordering is unusable.

[Classes with init's](https://github.com/GregHib/void/tree/034c94108988deb2d207250f6a1d9f71409f5b80) and a basic Script annotation to identify them also works, it's easier to convert and calls aren't too bad. However, startup time slows significantly for unknown reasons bringing the total startup time to 4-4.5s. Probably due to a mix of koin injection and InlineLogging. It could be parallelised however the Events tree is not type safe (a basic mutex does half the speed though), so lots of room for improvement.



Also once this work is complete. Updating to kotlin 2.0.0 isn't even feasible due to [NoSuchMethodError issue](https://youtrack.jetbrains.com/issue/KT-54513/NoSuchMethodError-on-access-to-value-class-implementing-an-interface-from-another-module) because Tile and similar value classes have Coordidate interfaces.

Ktor's major update also looks like it'll require significant work to migrate.

**Comment by GregHib** [comment]
At a bit of an impasse. Came up with a clean event object free annotation + ksp based solution. Converted most of it except a few bugs to be solved. It's clean, it's fast, startup times are down from 1.2s to .2s, although 500s of that is now passed off to initialisation of other classes and wasn't even due to scripts. But runtime has still gone from ~2.5s to 1.8-2s Runtime around the board is also faster.

However started to notice some issues when running non Main files, due to the way ksp does incremental processing it sometimes generates partial files which is no good when you always want everything linked together, so disabling ksp incremental is a must. That however means that any file change requires a full recompile and that's where I started to notice compiling taking longer than it should.

Compile times jumped from around 3s to 6s for using ksp with basic `@Script` annotations then to 13s with full annotations. The reason for this is fn.annotations taking up multiple seconds gathering up annotation information. This is essentially the same speed as if you were to use reflection to gather all the annotations (2.5s from testing).

So this is the impasse. Throw out a weeks work of converting due to slow compile times but better overall code health or spend more time figuring out if incremental is possible and even more fixing the remaining bugs.

**Comment by GregHib** [comment]
A few more failed attempts later, there's always a trade off outside of straight up writing a kotlin compiler plugin (no thanks). Reflection is fast to get the info but then you can do compilation in stages so it's not possible.
Grabbing metadata using a gradle task is very fast and reflection to create instances of classes also fast on startup, however calling those instance methods later was too slow (0.8-25ms vs 0.002 calling a method normally).

I think the best way forward is basic script annotations and then later adding a notification system where script classes extend and are grouped by interfaces that can all be called at once.
All the straight forward cases can then be converted and that will leave only the tricky ones with return types and cancellation.

Cancellation actually isn't too hard it's just accumulative boolean return types.

Command will need some custom code but isn't bad really.

The only problematic few are:

TimerStart
TimerTick
Teleport
Take/Consumable/Destroyable & other checkers
Combat

And I think it's worth distinguishing the basic notifications from the complex cases and perhaps a separate system for them

**Comment by GregHib** [comment]
#754 converted all scripts to a basic init {} format.
This is working well and will continue to exist for the foreseeable future now #758 is dependent on it.

#760 adds a first version of a "dispatch" system, it's much simpler than previous attempts and I will gradually convert basic existing events over to it.

- More performant both at startup and call-time
- A lot easier to debug
- A little tricker to setup tests for but not impossible
- "Event" classes - now "dispatchers" are quite compact to write albeit simple
- It doesn't support filtering so is really only suitable for "notification" events at the moment
- Could also be used for return types given a more complex calling method (i.e. if not null return loop)

The one use-case it really doesn't address is Interaction's which need both a filter and a way to check the filter without calling the method itself.

There's two obvious ways filters could be added, both using a map instead of a list in the dispatcher, the question is how to link the instance with the map keys.

One way would be to add annotations, collect them in the gradle task and write to the scripts file, then pass them to the dispatcher with the instance.

Another way would be to have in the interface a list which can be overridden, the dispatcher can then use that list store the instance. You have to be careful to avoid lists having different names, it could get quite messy, or you could reuse lists but then that would have it's own limitations of one type of npc per class.

Either way these solutions don't account for wildcards, at least with the annotation method wildcards can be precomputed as well

**Comment by GregHib** [comment]
Revisit 4?

The annotate interface approach works well in cases so far, spawn, move, timers, variables, level up etc...

and the performance gains are notable.

However attempting to convert interactions is more tricky, in no small part due to there being so many, namely 346 object operates and 412 npc operates.

The problem is a lot of the time there's more than just one per class and that means having multiple annotations and adding a when statement to separate them back out again, which is boiler plate, technically not as efficient, and is a lot of changes to do.

I'm wondering instead about sticking with an init {} approach, essentially the same as what is in use, however the interfaces would handle what occurs individually

```kotlin
interface TestApi {
    companion object {
        val map = mutableMapOf<String, suspend (Player, GameObject, String) -> Unit>()

        suspend fun approach(player: Player, target: GameObject, option: String) {
            (map["${option}:${target.def(player).id}"] ?: map[option])?.invoke(player, target, option)
        }
    }

    fun objectApproach(option: String, obj: String, handler: suspend (Player, GameObject, String) -> Unit) {
        map["$option:$obj"] = handler
    }
}

```

That allows backwards compatibility.. somewhat. with writing code directly in the init, but also allows registering just methods and referencing them.

```
@Script
class SteppingStones : TestApi {

    init {
        objectApproach("Jump-across", "lumbridge_swamp_stepping_stone", ::jumpAcross)
    }
}
```

The problems with this, is if you do use params, like playerSpawn { player -> this could get a bit unwieldy for inline calls and also wildcards. Which should still be process-able I think with some kind of lookup.

It'd probably also be possible to do a mix of both, notifications like player spawn don't need parameters so playerSpawn(::spawn) seems a bit redundant?

Not sure, needs more consideration.

**Comment by GregHib** [comment]
#797 marks the end of the latest migration. Ideally as described before lambda method references can be used rather than lambda calls inside the init method itself however this is more of a stylistic and best practise question which will also be hard to enforce considering the majority of the migrated code uses this format.

The new layout separates out handlers into their individual maps and lists, removing the majority of event classes in favour of direct method parameters, this has the trade-off of faster calls but in some cases not so great syntax, in the more complicated cases like combat handlers I've opted to keep the data classes for now.

The biggest change is most handlers now use the source character as an extension method so all calls no longer require typing the character e.g. `player.message()` becomes `message()`. This was discussed in #595 which I didn't do back then, however decided to do now, due to confusion it might cause, I accepted this trade-off because it really simplifies content scripts a lot, and it also simplified the whole Context, CancellableContext, SuspendableContext interface mess and nicely decoupled context from events. Which also had the side-effect of simplifying dialogues which can now be called like player.npc() although using player as the extension target keeps it more idiomatic. It does make queue's a bit messier although this can be addressed later if I notice it being an issue.

The separation does come at a cost, ~200ms extra startup time (also just under 2MB more RAM which is minor) I suspect previously having everything stored in one nested map was more cache efficient where now lots of maps spread over the code base requires lots of back and forth as scripts are loaded. However these structures can now be tested and optimised individually, they're easier to debug, and the parameter count has been decreased reducing the complexity of calls significantly though there still maybe room for improvement.

A new wildcarding system was also put in place, again also fractionally slower but significantly simpler and a bit more reliable, it's also hard to measure because it will knock off some compile time.
